"""new fields in user model

Revision ID: 026d0d510cf5
Revises: dccdc76e6e8a
Create Date: 2023-01-09 14:05:31.029585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026d0d510cf5'
down_revision = 'dccdc76e6e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
